---
- hosts: WebServer
  tasks:
  - name: Copy the file
    copy:
     src: /opt/prog1.sh
     dest: /home/ansible/prog.sh
     mode: 0755
  - name: change the line
    lineinfile:
     state: present  
     path: /home/ansible/prog.sh
     regexp: '^HOSTNAME='
     line: HOSTNAME={{ansible_hostname}}
  - name: Run the program
    shell: /home/ansible/prog.sh
    register: program_output
  - debug: msg="stdout={{ program_output }}"
